# Cloud SQL for Postgres — backs the MLflow tracking server and (optionally) Prefect.
#
# Two modes:
#   * Private IP: requires `vpc` module enabled + `private_services_connection`
#   * Public IP:  uses authorized_networks (dev-friendly)
#
# Passwords are generated by `random_password` and held in Terraform state ONLY
# for the lifetime of the resource — operators should rotate via Secret Manager
# after the first apply.

locals {
  all_databases = distinct(concat(var.databases, var.enable_prefect_db ? ["prefect"] : []))
  default_labels = merge(
    var.labels,
    {
      env       = var.env
      managed   = "terraform"
      component = "cloud-sql"
    }
  )
}

resource "random_password" "users" {
  for_each         = toset(var.users)
  length           = 24
  special          = true
  override_special = "_-+="
}

resource "google_sql_database_instance" "this" {
  project             = var.project_id
  name                = "${var.instance_name}-${var.env}"
  region              = var.region
  database_version    = var.database_version
  deletion_protection = var.deletion_protection

  settings {
    tier              = var.tier
    activation_policy = var.activation_policy
    availability_type = var.env == "prod" ? "REGIONAL" : "ZONAL"
    disk_size         = var.disk_size_gb
    disk_autoresize   = true
    disk_type         = "PD_SSD"
    user_labels       = local.default_labels

    backup_configuration {
      enabled                        = var.backup_enabled
      point_in_time_recovery_enabled = var.env == "prod"
      start_time                     = "03:00"
      backup_retention_settings {
        retained_backups = var.env == "prod" ? 14 : 7
        retention_unit   = "COUNT"
      }
    }

    ip_configuration {
      ipv4_enabled    = !var.use_private_ip
      private_network = var.use_private_ip ? var.private_network : null

      dynamic "authorized_networks" {
        for_each = var.use_private_ip ? [] : var.authorized_networks
        content {
          name  = authorized_networks.value.name
          value = authorized_networks.value.value
        }
      }
    }

    insights_config {
      query_insights_enabled  = true
      record_application_tags = true
      record_client_address   = false
    }

    maintenance_window {
      day          = 7 # Sunday
      hour         = 4
      update_track = "stable"
    }
  }

  # When using private IP we need the service-networking connection in place.
  depends_on = [
    # Module callers pass `private_services_connection` as a string ID; the var
    # is only used to enforce ordering. We can't `depends_on` a variable, so the
    # caller wires it via depends_on at the module block.
  ]

  lifecycle {
    ignore_changes = [
      # Patch updates from GCP shouldn't trigger replacement.
      settings[0].database_flags,
    ]
  }
}

resource "google_sql_database" "this" {
  for_each = toset(local.all_databases)
  project  = var.project_id
  name     = each.value
  instance = google_sql_database_instance.this.name
}

resource "google_sql_user" "this" {
  for_each = toset(var.users)
  project  = var.project_id
  name     = each.value
  instance = google_sql_database_instance.this.name
  password = random_password.users[each.value].result
}
